### ISSUE TITLE
Button showing there was an error but actually posts PR

### ISSUE THREAD

**Issue by PericlesTheo** [intercom/prfeed#3]
![Screenshot 2020-03-30 at 16 30 40](https://user-images.githubusercontent.com/1856436/77931388-04dcbe80-72a4-11ea-8b45-0c83947bcabb.png)

but actually it posts the PR on slack

The response looks fine as well
![Screenshot 2020-03-30 at 16 36 10](https://user-images.githubusercontent.com/1856436/77931829-a237f280-72a4-11ea-9e3f-af9878a58e39.png)

**Comment by pjestin** [comment]
Hey @PericlesTheo ! Is that an issue with PR feed, or with the browser plugin?

**Comment by PericlesTheo** [comment]
Very good point. It's probably the extension then if the response is 201.

**Comment by laurmurclar** [comment]
Thanks Pericles! Its the extension. In future, you're probably better off just opening the issue in the Intercom repo btw. I can move it there for you for now
